# Site settings
title: Stephan Fowler
subtitle: Product / Development 
#email: your-email@domain.com
description: "Currently at The Guardian"
baseurl: ""
url: "http://stephanfowler.com"

# Build settings
markdown: kramdown
permalink: pretty
