# Site settings
title: Stephan Fowler
subtitle: Archive 
#email: your-email@domain.com
description: ""
baseurl: ""
url: "http://stephanfowler.com"

# Build settings
markdown: kramdown
permalink: pretty
