# Site settings
title: Stephan Fowler
subtitle: Product Development 
#email: your-email@domain.com
description: "Websites for newspaper companies. Currently at The Guardian."
baseurl: ""
url: "http://stephanfowler.com"

# Build settings
markdown: kramdown
permalink: pretty
