# Site settings
title: Stephan Fowler
subtitle: Archive 
#email: your-email@domain.com
description: ""
baseurl: ""
url: "http://stephanfowler.com"

# Build settings
markdown: kramdown
permalink: pretty

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
